# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#"1=北海道", 2="東北", 3="関東", 4="中部", 5="近畿", 6="中国", 7="四国", 8="九州"
Prefecture.create(name:"北海道", area:"1")

Prefecture.create(name:"青森県", area:"2")
Prefecture.create(name:"岩手県", area:"2")
Prefecture.create(name:"宮城県", area:"2")
Prefecture.create(name:"秋田県", area:"2")
Prefecture.create(name:"山形県", area:"2")
Prefecture.create(name:"福島県", area:"2")

Prefecture.create(name:"茨城県", area:"3")
Prefecture.create(name:"栃木県", area:"3")
Prefecture.create(name:"群馬県", area:"3")
Prefecture.create(name:"埼玉県", area:"3")
Prefecture.create(name:"千葉県", area:"3")
Prefecture.create(name:"東京都", area:"3")
Prefecture.create(name:"神奈川県", area:"3")

Prefecture.create(name:"新潟県", area:"4")
Prefecture.create(name:"富山県", area:"4")
Prefecture.create(name:"石川県", area:"4")
Prefecture.create(name:"福井県", area:"4")
Prefecture.create(name:"山梨県", area:"4")
Prefecture.create(name:"長野県", area:"4")
Prefecture.create(name:"岐阜県", area:"4")
Prefecture.create(name:"静岡県", area:"4")
Prefecture.create(name:"愛知県", area:"4")
Prefecture.create(name:"三重県", area:"4")

Prefecture.create(name:"滋賀県", area:"5")
Prefecture.create(name:"京都府", area:"5")
Prefecture.create(name:"大阪府", area:"5")
Prefecture.create(name:"兵庫県", area:"5")
Prefecture.create(name:"奈良県", area:"5")
Prefecture.create(name:"和歌山県", area:"5")

Prefecture.create(name:"鳥取県", area:"6")
Prefecture.create(name:"島根県", area:"6")
Prefecture.create(name:"岡山県", area:"6")
Prefecture.create(name:"広島県", area:"6")
Prefecture.create(name:"山口県", area:"6")

Prefecture.create(name:"徳島県", area:"7")
Prefecture.create(name:"香川県", area:"7")
Prefecture.create(name:"愛媛県", area:"7")
Prefecture.create(name:"高知県", area:"7")

Prefecture.create(name:"福岡県", area:"8")
Prefecture.create(name:"佐賀県", area:"8")
Prefecture.create(name:"長崎県", area:"8")
Prefecture.create(name:"熊本県", area:"8")
Prefecture.create(name:"大分県", area:"8")
Prefecture.create(name:"宮崎県", area:"8")
Prefecture.create(name:"鹿児島県", area:"8")
Prefecture.create(name:"沖縄県", area:"8")

Shrine.create(name:"北海道神宮", address:"札幌市中央区宮ケ丘", prefecture_id:"1")
Shrine.create(name:"岩木山神社", address:"弘前市百沢字寺沢27", prefecture_id:"2")
Shrine.create(name:"三ツ石神社", address:"盛岡市名須川町２−１", prefecture_id:"3")
Shrine.create(name:"鹽竈神社", address:"塩竈市一森山１−１", prefecture_id:"4")
Shrine.create(name:"唐松神社", address:"大仙市協和境下台８４", prefecture_id:"5")
Shrine.create(name:"出羽神社", address:"鶴岡市羽黒町手向字羽黒山33", prefecture_id:"6")
Shrine.create(name:"伊佐須美神社", address:"大沼郡会津美里町字宮林甲４３７７", prefecture_id:"7")
Shrine.create(name:"鹿島神宮", address:"鹿嶋市宮中２３０６−１", prefecture_id:"8")
Shrine.create(name:"太平山神社", address:"栃木市平井町６５９", prefecture_id:"9")
Shrine.create(name:"榛名神社", address:"高崎市榛名山町８４９", prefecture_id:"10")
Shrine.create(name:"武藏國一之宮 氷川神社", address:"さいたま市大宮区高鼻町１−４０７", prefecture_id:"11")
Shrine.create(name:"香取神宮", address:"香取市香取１６９７−１", prefecture_id:"12")
Shrine.create(name:"明治神宮", address:"渋谷区代々木神園町１−１", prefecture_id:"13")
Shrine.create(name:"鶴岡八幡宮", address:"鎌倉市雪ノ下２丁目１−３１", prefecture_id:"14")
Shrine.create(name:"彌彦神社", address:"西蒲原郡弥彦村大字弥彦２８８７−２", prefecture_id:"15")
Shrine.create(name:"日枝神社", address:"富山市山王町４−１２", prefecture_id:"16")
Shrine.create(name:"白山比咩神社", address:"白山市三宮町ニ−１０５−１", prefecture_id:"17")
Shrine.create(name:"毛谷黒龍神社", address:"福井市毛矢３丁目８−１", prefecture_id:"18")
Shrine.create(name:"差出磯大嶽山神社", address:"山梨市南１３７６−１", prefecture_id:"19")
Shrine.create(name:"諏訪大社", address:"諏訪市中洲宮山１", prefecture_id:"20")
Shrine.create(name:"伊奈波神社", address:"岐阜市伊奈波通１丁目１", prefecture_id:"21")
Shrine.create(name:"来宮神社", address:"熱海市西山町４３−１", prefecture_id:"22")
Shrine.create(name:"熱田神宮", address:"名古屋市熱田区神宮1-1-1", prefecture_id:"23")
Shrine.create(name:"伊勢神宮", address:"伊勢市宇治館町１", prefecture_id:"24")
Shrine.create(name:"多賀大社", address:"犬上郡多賀町大字多賀６０４", prefecture_id:"25")
Shrine.create(name:"石清水八幡宮", address:"八幡市八幡高坊30", prefecture_id:"26")
Shrine.create(name:"住吉大社", address:"大阪市住吉区住吉2-9-89", prefecture_id:"27")
Shrine.create(name:"生田神社", address:"神戸市中央区下山手通一丁目", prefecture_id:"28")
Shrine.create(name:"春日大社", address:"奈良市春日野町160", prefecture_id:"29")
Shrine.create(name:"熊野本宮大社", address:"田辺市本宮町本宮1100", prefecture_id:"30")
Shrine.create(name:"白兎神社", address:"鳥取市白兎６０３", prefecture_id:"31")
Shrine.create(name:"出雲大社", address:"出雲市大社町杵築東195", prefecture_id:"32")
Shrine.create(name:"吉備津神社", address:"岡山市北区吉備津９３１", prefecture_id:"33")
Shrine.create(name:"厳島神社", address:"廿日市市宮島町1-1", prefecture_id:"34")
Shrine.create(name:"防府天満宮", address:"防府市松崎町１４−１", prefecture_id:"35")
Shrine.create(name:"大麻比古神社", address:"鳴門市大麻町板東広塚１３", prefecture_id:"36")
Shrine.create(name:"金刀比羅宮", address:"仲多度郡琴平町８９２−１", prefecture_id:"37")
Shrine.create(name:"大山祇神社", address:"今治市大三島町宮浦宮浦３３２７", prefecture_id:"38")
Shrine.create(name:"土佐國一之宮 土佐神社", address:"高知市一宮しなね２丁目１６−１", prefecture_id:"39")
Shrine.create(name:"太宰府天満宮", address:"太宰府市宰府4丁目7番1号", prefecture_id:"40")
Shrine.create(name:"祐徳稲荷神社", address:"鹿島市古枝乙１８５５", prefecture_id:"41")
Shrine.create(name:"諏訪神社", address:"長崎市上西山町１８−１５", prefecture_id:"42")
Shrine.create(name:"加藤神社", address:"熊本市中央区本丸２−１", prefecture_id:"43")
Shrine.create(name:"宇佐神宮", address:"宇佐市南宇佐２８５９", prefecture_id:"44")
Shrine.create(name:"鵜戸神宮", address:"日南市大字宮浦3232", prefecture_id:"45")
Shrine.create(name:"霧島神宮", address:"霧島市霧島田口2608番地5号", prefecture_id:"46")
Shrine.create(name:"波上宮", address:"那覇市若狭1-25-11", prefecture_id:"47")